title: "Vitor Py"
author: "Vitor Py"
subtitle: "I write about software."

url: "https://vitorpy.com"
#baseurl: "/"

footer_only_homepage: true
footer_url: "https://github.com/rahul-bothra"
footer_text: "Theme by rahul-bothra"

profile-picture: https://avatars1.githubusercontent.com/u/12871
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Twitter"
   absolute-link: "https://twitter.com/PyVitor"
 - name: "GitHub"
   absolute-link: "https://github.com/vitorpy"
 - name: "LinkedIn"
   absolute-link: "https://linkedin.com/in/vitorpy"