title: "Vitor Py"
author: "Vitor Py"
subtitle: ""

url: "https://vitorpy.com"
baseurl: ""

favicon_location: assets/favicon.ico
github_user: vitorpy

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

exclude:
  - nginx.conf
  - deploy.sh
  - extract_icons.py
  - package.json
  - .pre-commit-config.yaml
  - commitlint.config.ts

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

navbar:
 - name: "About"
   link: ""
 - name: "Random Notes"
   link: "blog"
 - name: "x-twitter"
   absolute_link: "https://x.com/PyVitor"
 - name: "bluesky"
   absolute_link: "https://bsky.app/profile/pyvitor.bsky.social"
 - name: "github"
   absolute_link: "https://github.com/vitorpy"
