title: "Vitor Py Braga"
author: "Vitor Py Braga"
subtitle: "I write about software."

url: "https://vitorpy.com"
#baseurl: "/"

footer_only_homepage: true
footer_url: "https://github.com/rahul-bothra"
footer_text: "Theme by rahul-bothra"

profile-picture: https://avatars1.githubusercontent.com/u/12871
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

plugins:
  - jekyll-feed
  - jekyll/mastodon_webfinger

mastodon:
  username: vitorpy
  instance: sigmoid.social

navbar:
 - name: "About"
   link: "about"
 - name: "GitHub"
   absolute-link: "https://github.com/vitorpy"
 - name: "Mastodon"
   absolute-link: "https://sigmoid.social/@vitorpy"
 - name: "Twitter"
   absolute-link: "https://twitter.com/PyVitor"