title: "Vitor Py"
author: "Vitor Py"
subtitle: ""

url: "https://vitorpy.com"
baseurl: ""

favicon_location: assets/favicon.ico
github_user: vitorpy

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

navbar:
 - name: "Writing"
   link: "blog"
 - name: "warpcast"
   farcast: "https://warpcast.com/vitorpy"
 - name: "github"
   absolute_link: "https://github.com/vitorpy"
 - name: "x-twitter"
   absolute_link: "https://twitter.com/PyVitor"