title: "Vitor Py Braga"
author: "Vitor Py Braga"
subtitle: ""

url: "https://vitorpy.com"
baseurl: ""

footer_only_homepage: true
footer_url: "https://github.com/rahul-bothra"
footer_text: "Theme by rahul-bothra"

profile_picture: https://avatars1.githubusercontent.com/u/12871
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "Writing"
   link: "blog"
 - name: "github"
   absolute-link: "https://github.com/vitorpy"
 - name: "x-twitter"
   absolute-link: "https://twitter.com/PyVitor"