name = "Vitorpy"
license = "MIT"
description = "A minimalist Zenburn-inspired theme for vitorpy.com"
homepage = "https://vitorpy.com"
tags = ["minimal", "monospace", "zenburn"]
features = ["blog"]
min_version = "0.41.0"

[author]
  name = "Vitor Py"
  homepage = "https://vitorpy.com"