name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build site
        run: hugo --minify

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: |
          rsync -avz --delete \
            -e "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" \
            --exclude='.git' \
            --exclude='node_modules' \
            public/ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/vitorpy.com/

      - name: Deploy nginx config if changed
        run: |
          # Check if nginx.conf exists and copy if needed
          if [ -f nginx.conf ]; then
            ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no \
              ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
              "mkdir -p /tmp/deploy"

            scp -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no \
              nginx.conf ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/tmp/deploy/nginx.conf

            ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no \
              ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
              "if ! diff -q /tmp/deploy/nginx.conf /etc/nginx/conf.d/vitorpy.conf > /dev/null 2>&1; then \
                cp /tmp/deploy/nginx.conf /etc/nginx/conf.d/vitorpy.conf && \
                nginx -t && \
                systemctl reload nginx && \
                echo 'Nginx config updated and reloaded'; \
              else \
                echo 'Nginx config unchanged'; \
              fi"
          fi

      - name: Set permissions
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
            "chown -R nginx:nginx /var/www/vitorpy.com && chmod -R 755 /var/www/vitorpy.com"

      - name: Cleanup
        if: always()
        run: rm -f ~/.ssh/deploy_key